name: Helm Publish

on:
  workflow_call:

jobs:
  puiblish-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    name: Publish Chart
    steps:
      - uses: actions/checkout@v1
      - uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          charts-folder: ./charts
          deploy-branch: release