name: Helm Publish

on:
  workflow_call:

jobs:
  puiblish-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    name: Publish Chart
    steps:
      - uses: actions/checkout@v4
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          pages_branch: release