name: Helm Publish

on:
  workflow_call:
    inputs:
      version:
        description: "Version to tag the chart with"
        required: false
        type: string

jobs:
  puiblish-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    name: Publish Chart
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v3
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: Run Helm
        run: |
          mkdir -p .releases
          helm package ./charts/dropshipper-ui/ --dependency-update --destination .releases/
          helm repo index .releases/ --url https://lacuna-systems.github.io/dropshipper-ui/
      - name: Commit And Push Chart Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Added the helm chart for ${{ github.event.inputs.version }}"
          file_pattern: ".releases/*"